apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python-service
spec:
  type: NodePort                # Macht den Service von außen erreichbar (für Minikube)
  selector:
    app: python-service
  ports:
  - protocol: TCP
    port: 5000                  # Port innerhalb des Clusters
    targetPort: 5000           # Port im Container
    nodePort: 30000            # Externer Port (30000-32767)
